//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.WebUI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCeza
    {
        public int Id { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<decimal> ParaCezasi { get; set; }
        public Nullable<int> HareketId { get; set; }
    
        public virtual TblHareket TblHareket { get; set; }
        public virtual TblUye TblUye { get; set; }
    }
}
