//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.WebUI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHareket()
        {
            this.TblCeza = new HashSet<TblCeza>();
        }
    
        public int Id { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> IadeTarihi { get; set; }
        public Nullable<bool> Durumu { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCeza> TblCeza { get; set; }
        public virtual TblKitap TblKitap { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblUye TblUye { get; set; }
    }
}
